import fs from 'node:fs';
import path from 'node:path';
import { site, projects, experience } from '../src/site.js';

const out = path.resolve('dist');
const escape = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
const diagonal = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12"/></svg>';
const download = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/></svg>';
const nav = (active) => `<a class="skip-link" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="/" aria-label="Nicholas Gittins, home"><span class="monogram" aria-hidden="true">ng.</span><span class="brand-name">Nicholas Gittins</span></a><nav aria-label="Main navigation"><a ${active==='work'?'aria-current="page"':''} href="/#work">Selected work</a><a ${active==='about'?'aria-current="page"':''} href="/about/">About</a><a ${active==='cv'?'aria-current="page"':''} href="/cv/">CV ${diagonal}</a>${site.email?`<a href="mailto:${escape(site.email)}">Contact ${diagonal}</a>`:''}</nav></header>`;
const footer = () => `<footer class="footer wrap"><div class="footer-top"><p class="eyebrow">Professional portfolio</p><a class="footer-name" href="/">Nicholas Gittins</a><div class="footer-links"><a class="text-link" href="/cv/">View curriculum vitae ${arrow}</a>${site.email?`<a class="text-link" href="mailto:${escape(site.email)}">Get in touch ${diagonal}</a>`:''}</div></div><div class="footer-bottom"><span>Archives · Special collections · Digital preservation</span><a href="#top">Back to top ↑</a></div></footer>`;
function page({title, description=site.description, body, active='', cls=''}) {
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#f6f4ee"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><title>${escape(title)}</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/newsreader.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/dm-sans.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/site.js" defer></script></head><body id="top" class="${cls}">${nav(active)}<main id="main">${body}</main>${footer()}</body></html>`;
}
function write(url, html) {const file=path.join(out,url);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);}
const projectRows = projects.map(p=>`<a class="project-row group" data-reveal href="/work/${p.slug}/"><span class="project-number tabular-nums">${p.number}</span><div><p class="eyebrow">${p.category}</p><h3>${p.shortTitle}</h3><p class="project-summary">${p.summary}</p><p class="project-institution">${p.institution}</p></div><span class="project-end"><span class="tabular-nums">${p.dates}</span><span class="project-arrow">${arrow}</span></span></a>`).join('');
write('index.html',page({title:'Nicholas Gittins — Archives & Special Collections',active:'work',body:`
<section class="hero wrap">
 <div class="hero-intro"><p class="eyebrow enter">Archives & special collections</p><h1 class="enter delay-1">Nicholas<br>Gittins</h1><p class="hero-description enter delay-2">Information professional with experience in archival processing, digital preservation, collections research, and public engagement.</p><p class="hero-qualification enter delay-3">MLIS, University of Pittsburgh · 2025</p><div class="hero-actions enter delay-3"><a class="button" href="#work">Selected work ${arrow}</a><a class="text-link" href="/cv/">View CV ${diagonal}</a></div></div>
 <figure class="hero-figure portrait-panel enter delay-2"><div class="portrait-mount"><div class="portrait-window"><img src="/assets/nicholas-gittins-original.png" width="720" height="720" alt="Nicholas Gittins" fetchpriority="high"></div></div><figcaption><span>Nicholas Gittins</span><span>Archives & special collections</span></figcaption></figure>
</section>
<div class="intro-note wrap"><span class="eyebrow">Professional background</span><p>University archives, rare books, digital initiatives, and public library services, with experience at Carnegie Mellon, the University of Pittsburgh, Carnegie Library of Pittsburgh, and Utah State.</p></div>
<section class="section wrap" id="work"><div class="section-heading"><div><p class="eyebrow">01 / Portfolio</p><h2>Selected archival work</h2></div><p>Collection processing, preservation metadata,<br>and oral history description.</p></div><div class="project-list">${projectRows}</div></section>
<section class="practice-section"><div class="wrap practice-inner"><div><p class="eyebrow">02 / Areas of practice</p><h2>Professional practice</h2><p class="practice-intro">My work combines collection description and preservation with research support, instruction, and outreach.</p><a class="text-link" href="/about/">Professional background ${arrow}</a><figure class="archive-detail"><img src="/assets/carnegie-reading-room-1890.jpg" alt="The Carnegie Library reading room in Allegheny City, circa 1890" width="1024" height="808" loading="lazy"><figcaption><a href="https://www.loc.gov/item/2007684794/" target="_blank" rel="noopener noreferrer">Carnegie Library, c. 1890 · Library of Congress ${diagonal}<span class="sr-only"> (opens in a new tab)</span></a></figcaption></figure></div><div class="practice-list"><div data-reveal><span class="tabular-nums">01</span><div><h3>Archival processing</h3><p>Process collections, develop finding aids, and document workflows so materials can be understood in context.</p></div></div><div data-reveal><span class="tabular-nums">02</span><div><h3>Digital preservation</h3><p>Prepare accurate metadata and attend to the details that support long-term access to digital assets.</p></div></div><div data-reveal><span class="tabular-nums">03</span><div><h3>Research and outreach</h3><p>Connect collections with researchers, students, and communities through exhibits, instruction, and outreach.</p></div></div></div></div></section>
<section class="section wrap experience-preview"><div><p class="eyebrow">03 / Career</p><h2>Professional experience</h2><p class="measure">My experience spans university archives, rare books, digital initiatives, and public library services.</p><a class="text-link" href="/cv/">View full experience ${arrow}</a></div><div class="institution-list"><div><span>Carnegie Mellon University</span><p>Architecture Archives</p></div><div><span>University of Pittsburgh</span><p>Digital Preservation · MLIS, 2025</p></div><div><span>Carnegie Library of Pittsburgh</span><p>Rare Books & Special Collections · Adult Services</p></div><div><span>Utah State University</span><p>Fife Folklore Archives · Open Education · Library Services</p></div></div></section>`}));

for (const [i,p] of projects.entries()) {
const next=projects[(i+1)%projects.length];
write(`work/${p.slug}/index.html`,page({title:`${p.shortTitle} — Nicholas Gittins`,description:p.summary,body:`<article class="case-study"><header class="case-header wrap"><a class="back-link" href="/#work">← Selected work</a><p class="eyebrow enter">${p.number} / ${p.category}</p><h1 class="enter delay-1">${p.title}</h1><div class="case-meta"><div><span>Institution</span><p>${p.institution}</p></div><div><span>Role</span><p>${p.role}</p></div><div><span>Years</span><p>${p.dates}</p></div></div></header><div class="case-body wrap"><aside><p class="eyebrow">Areas of practice</p><ul class="tool-list">${p.tools.map(t=>`<li>${t}</li>`).join('')}</ul></aside><div class="case-prose"><p class="case-lead">${p.intro}</p>${p.sections.map(([h,t])=>`<section data-reveal><h2>${h}</h2><p>${t}</p></section>`).join('')}<section><h2>Contributions</h2><ul class="contributions">${p.outputs.map(t=>`<li>${t}</li>`).join('')}</ul></section><section><h2>Related experience</h2><p>${p.related}</p>${p.external?`<a class="text-link external-link" href="${p.external.url}" target="_blank" rel="noopener noreferrer">${p.external.label} ${diagonal}<span class="sr-only"> (opens in a new tab)</span></a>`:''}</section></div></div><a class="next-project wrap" href="/work/${next.slug}/"><span class="eyebrow">Next project / ${next.number}</span><span>${next.shortTitle}</span>${arrow}</a></article>`}));
}

write('about/index.html',page({title:'About — Nicholas Gittins',active:'about',body:`<section class="about-hero wrap"><p class="eyebrow enter">Professional background</p><h1 class="enter delay-1">About Nicholas</h1><div class="about-intro"><p class="case-lead">I’m an information professional with experience across archives, special collections, digital preservation, and library services.</p><p>My work has taken me from Utah State University’s library collections and Fife Folklore Archives to rare books at Carnegie Library of Pittsburgh, digital preservation at the University of Pittsburgh, and architectural records at Carnegie Mellon University.</p></div></section><section class="section wrap about-grid"><div><p class="eyebrow">01 / Practice</p><h2>Professional interests</h2></div><div class="case-prose"><p>I’m interested in the connections between collections and the communities they serve. That has meant working with a donor to describe oral history materials, helping researchers access rare books, teaching people to use digital resources, and developing exhibitions from archival collections.</p><p>I bring experience coordinating projects and supporting people: supervising student teams, developing workflows, and guiding open education projects from consultation through publication.</p><p>My academic background in history, Ancient Greek, and Latin informs the close attention I bring to records and their context.</p></div></section><section class="section wrap about-grid education"><div><p class="eyebrow">02 / Qualifications</p><h2>Education</h2></div><div><div class="education-item"><span class="eyebrow">University of Pittsburgh · December 2025</span><h3>Master of Library and Information Science</h3></div><div class="education-item"><span class="eyebrow">Utah State University · May 2017</span><h3>Bachelor of Arts in History</h3><p>Double minor in Ancient Greek and Latin</p></div><div class="education-item"><span class="eyebrow">University of Utah · July–August 2017</span><h3>Greece, from Minoan to Modern Times</h3><p>Non-degree study abroad</p></div></div></section><section class="section wrap about-grid"><div><p class="eyebrow">03 / Skills</p><h2>Tools and methods</h2></div><div class="skills-columns"><div><h3>Archives & libraries</h3><p>ArchivesSpace, Preservica, Sierra ILS, OCLC, CollectionHQ, Springshare / LibApps</p></div><div><h3>Digital & project work</h3><p>WordPress, Airtable, Microsoft Office, Google Suite, Trello, Python, VS Code</p></div><div><h3>People & collections</h3><p>Collections research, project management, staff training, exhibits, outreach, and research support</p></div></div></section>`}));

write('cv/index.html',page({title:'Curriculum Vitae — Nicholas Gittins',active:'cv',cls:'cv-page',body:`<header class="cv-header wrap"><div><p class="eyebrow">Experience & education</p><h1>Curriculum vitae</h1><p>Nicholas Gittins · Archives, special collections, and digital preservation</p></div><div class="download-actions"><a class="button" href="/assets/nicholas-gittins-cv.pdf" download>Download full CV <span class="file-type">PDF</span>${download}</a><a class="text-link" href="/assets/nicholas-gittins-cv.docx" download>Word version ${download}</a></div></header><section class="cv-section wrap"><h2>Professional experience</h2><div>${experience.map(([date,role,org,desc])=>`<div class="cv-role"><span class="eyebrow tabular-nums">${date}</span><div><h3>${role}</h3><p class="organization">${org}</p><p>${desc}</p></div></div>`).join('')}</div></section><section class="cv-section wrap"><h2>Archives internship</h2><div class="cv-role"><span class="eyebrow">2019–2022</span><div><h3>Special Collections and Archives Intern</h3><p class="organization">Utah State University · Fife Folklore Archives</p><p>Created metadata for the Grant Bulltail Apsáalooke Oral History Collection in collaboration with Grant Bulltail, including travel to Crow Agency, Montana.</p><a class="text-link" href="/work/oral-history/">Read about the collection ${arrow}</a></div></div></section><section class="cv-section wrap"><h2>Education</h2><div><div class="cv-role"><span class="eyebrow">2025</span><div><h3>Master of Library and Information Science</h3><p>University of Pittsburgh</p></div></div><div class="cv-role"><span class="eyebrow">2017</span><div><h3>B.A. History</h3><p>Utah State University · Double minor in Ancient Greek and Latin</p></div></div><div class="cv-role"><span class="eyebrow">2017</span><div><h3>Greece, from Minoan to Modern Times</h3><p>University of Utah · Non-degree study abroad</p></div></div></div></section><section class="cv-section wrap"><h2>Selected exhibits & presentations</h2><div>${[
['2025','Select Edward B. Lee Sketches and Site Photographs of Greenlee Field, Home of the Pittsburgh Crawfords','Exhibit · CMU Architecture Archives'],
['2025','Building Together: Connections and Community','Community engagement · Churchill, Pennsylvania'],
['2025','Mr. Cornelia Brierly, Expanding Representation and Context in the Architecture Archives at CMU','Presentation · MARAC, Harrisburg, Pennsylvania'],
['2023','Finding Your Voice: The Many Mediums of Expression','Rare books exhibit, online publication, and interactive exhibit · Carnegie Library of Pittsburgh'],
['2023','Found Favorites','Rare books exhibit · Carnegie Library of Pittsburgh'],
['2023','Willa Cather and Pittsburgh','Rare books exhibit · Carnegie Library of Pittsburgh'],
['2022','None of our Business: Examining the Economics and Business Dynamics of the Library and Information Industry','Presentation · Utah Library Association'],
['2020','Iwaalawiloxhbaka, How We Lived: The Grant Bulltail Apsáalooke Oral History Collection','Presentation · Utah Library Association'],
].map(([y,t,d])=>`<div class="cv-role"><span class="eyebrow">${y}</span><div><h3>${t}</h3><p>${d}</p></div></div>`).join('')}</div></section><section class="cv-section wrap"><h2>Leadership & service</h2><div class="case-prose"><h3>UALC OER Committee Chair</h3><p>Fall 2021–summer 2022. Collaborated with Utah Education Network and higher education colleagues on publishing guides, workshops, and statewide open education support.</p><h3>Selected library service</h3><p>USU Libraries’ Harmful Language in Collections Statement Committee; Scholarly Communications and Open Access Committee; Diversity, Equity, Inclusion, and Accessibility Task Force and Learning Circle; and Student Supervisors Community of Practice.</p><a class="text-link" href="/assets/nicholas-gittins-cv.pdf" download>Download the complete CV for all service, awards, and presentations ${download}</a></div></section>`}));
write('404.html',page({title:'Page not found — Nicholas Gittins',body:`<section class="section wrap not-found"><p class="eyebrow">404 / Page not found</p><h1>Page not found</h1><p>The address may have changed. You can find my projects and experience from the homepage.</p><a class="button" href="/">Return home ${arrow}</a></section>`}));
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
fs.copyFileSync('src/_headers',path.join(out,'_headers'));
fs.copyFileSync('src/site-client.js',path.join(out,'assets/site.js'));
fs.copyFileSync('src/assets/nicholas-gittins-original.png',path.join(out,'assets/nicholas-gittins-original.png'));
for (const file of ['nicholas-gittins-cv.pdf','carnegie-reading-room-1890.jpg']) fs.copyFileSync(path.join('src/assets',file),path.join(out,'assets',file));
fs.copyFileSync('BigCV_nick.docx',path.join(out,'assets/nicholas-gittins-cv.docx'));
for (const [source,target] of [['newsreader/files/newsreader-latin-wght-normal.woff2','newsreader.woff2'],['newsreader/files/newsreader-latin-wght-italic.woff2','newsreader-italic.woff2'],['dm-sans/files/dm-sans-latin-wght-normal.woff2','dm-sans.woff2']]) fs.copyFileSync(`node_modules/@fontsource-variable/${source}`,path.join(out,'assets',target));
fs.writeFileSync(path.join(out,'assets/favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="4" fill="#742f3e"/><text x="10" y="45" fill="#f6f4ee" font-family="Georgia,serif" font-size="38">ng</text></svg>');
fs.mkdirSync(path.join(out, 'assets/licenses'), {recursive:true});
for(const font of ['newsreader','dm-sans']) fs.copyFileSync(`node_modules/@fontsource-variable/${font}/LICENSE`, path.join(out, 'assets/licenses', `${font}.txt`));
console.log('Built 7 static pages, local fonts, and CV downloads.');
